### ISSUE TITLE
examples03: HttpError

### ISSUE THREAD

**Issue by dingjy0714** [kaust-halo/geeet#26]
An error occurred when running geeet-main\examples\notebooks\03_eepredefined_landsat_era5. After analyzing the reason, it was found that https://earthengine.googleapis.com/v1/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json could not be opened. How to solve this problem?
![Uploading 1710898911733.png…]()

**Comment by lopezvoliver** [comment]
@dingjy0714 could you please provide more information? 

I think the image you were trying to upload failed to upload. 

Which cell is the one giving you the error and what error are you getting?

**Comment by lopezvoliver** [comment]
@dingjy0714  Is this the error you got?

```
EEException: Collection.first: Error in map(ID=1_1_LE07_172039_20230403):
Image.select: Pattern 'SR_3' did not match any bands. Available bands: [SR_B1, SR_B2, SR_B3, SR_B4, SR_B5, SR_B7, SR_ATMOS_OPACITY, SR_CLOUD_QA, ST_B6, ST_ATRAN, ST_CDIST, ST_DRAD, ST_EMIS, ST_EMSD, ST_QA, ST_TRAD, ST_URAD, QA_PIXEL, QA_RADSAT]
```

This was caused by a [bug in the L7 band names](https://github.com/kaust-halo/geeet/commit/e0dff29d01c439973934d79dcc4cf250c3ee4808) 

I will try to make a newer release soon to pip and conda-forge, but in the meantime you can install the updated code from github using pip:

```bash
pip uninstall geeet      # Uninstall your current geeet version
pip install git+https://github.com/kaust-halo/geeet.git   # Install the newest one
```

**Comment by dingjy0714** [comment]
@lopezvoliver Thank you very much! I have solved this problem now.

I'm really sorry for not replying to you in time. 
Thanks again.
