### ISSUE TITLE
Questions about the accuracy of calculations

### ISSUE THREAD

**Issue by dingjy0714** [kaust-halo/geeet#33]
I tried to use this code to calculate the daily evapotranspiration data of a farmland during  the growing period of the crop. 

However, there is a big difference between the calculated results and the ETMonitor product. R-squared can reach more than 0.6 in June and July. Surprisingly, other months (April, May, and August) have an R-squared of less than 0.01, and their RMSE values are also high.

Is this problem caused by the TSEB model or this code?  And what should I do to to improve the accuracy?

Looking forward to your reply!

**Comment by lopezvoliver** [comment]
Hi @dingjy0714 , sorry for the very late response. Not sure what the specific problem here is, as I am not familiar with the ETMonitor product. More generally, inter-comparison of satellite-based ET models is still an active research topic, so I wouldn't be surprised when encountering differences between models. Please open a new issue if you spot a specific error in the code or encounter an unexpected issue.
